### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by SrMouraSilva** [sourcelair/ceryx#53]
Hello, I could not find the project documentation, api or even a quickstart

Is there a document?

**Comment by MikeKMiller** [comment]
Yes, please add at least basic documentation beyond using with docker, as we do not use docker.

**Comment by ruledio** [comment]
Docker is the best way to package something like ceryx what sort of documentation are you after? 

Currently there is a quickstarter guide for running with docker 

But I do agree there should be some documentation as I found it quite difficult to get up and running, there seem to be some confusing stale branches and docker image tags.

**Comment by SrMouraSilva** [comment]
API
* path
* methods
* params and body request
* body response
* Auth?
* Port?

Quickstart
* There are a list of parameters, but all are required? https://github.com/sourcelair/ceryx#configuration
* It is not clear to me if I use the dockercompose available in the repository root can be used in production
* Is required a host, but if I will test in a local machine? Will work? 
* The Development comments about the initial state of the application, but not about the steps required for a people configure a local development

**Comment by parisk** [comment]
Hello everyone. I will reply to each topic separately.

## Docs

I see that a confusing part of our documentation is that we do not mention that you have to set up the DNS records pointing to Ceryx, in order to get things working.

We will update the docs within the coming days, since the project has already matured internally for us.

For a quick-start guide take a look at: https://github.com/sourcelair/ceryx#quick-bootstrap.

## Packaging

We can definitely distribute ceryx-api as a Python package, but I have no good idea about how we could distribute the server which is based on NGINX, OpenResty and Lua, besides as a Docker image. 

Any thoughts? I can't promise we will do so, but I would love to hear any alternatives.

**Comment by MikeKMiller** [comment]
Perhaps we could start with the prerequisites to install for those of use that are not looking to use with docker containers. i.e... versions for OpenResty, Lua, Python, and any required modules. I have gotten it partially running outside of docker, however getting errors that appear to be related to incompatible versions and install locations.

Thank you in advance, this platform has amazing potential.

**Comment by MikeKMiller** [comment]
Could we please in the meantime, get more detail on the setup required for the DNS?

**Comment by akalipetis** [comment]
The DNS is required only if you're willing to use domain names as backend targets. Currently, we're using the Docker DNS server since we're using internal DNS records, but if you just use normal DNS records setting something like 8.8.8.8 should be fine.

**Comment by reyou** [comment]
Can you please at least supply some usage examples, how redirect works etc?

Like this one:
http://openresty.org/en/dynamic-routing-based-on-redis.html

I believe this project should even add more abstractions on top of what openresty supplies.
Would it be something you will be considering?

Thanks!

**Comment by parisk** [comment]
Thanks for the comments everybody. I prepared a PR to improve the documentation in the README: https://github.com/sourcelair/ceryx/pull/57.

It should land in master branch soon, after we are confident with the content.
