### ISSUE TITLE
docker run produces with default values unary operator expected error

### ISSUE THREAD

**Issue by gurumark** [sourcelair/ceryx#72]
docker run -d \
--name ceryx \
-p 80:80 -p 443:443 \
--restart=always \
sourcelair/ceryx usr/local/openresty/bin/openresty -g - daemon off

I get:

+ '[' == true ']'
/entrypoint.sh: line 5: [: ==: unary operator expected
+ export CERYX_LOG_LEVEL=info
+ CERYX_LOG_LEVEL=info
+ /usr/local/bin/dockerize -template /usr/local/openresty/nginx/conf/nginx.conf.tmpl:/usr/local/openresty/nginx/conf/nginx.conf -template /usr/local/openresty/nginx/conf/ceryx.conf.tmpl:/usr/local/openresty/nginx/conf/ceryx.conf -wait tcp://redis:6379
2019/08/31 13:24:02 Waiting for: tcp://redis:6379
2019/08/31 13:24:02 Connected to tcp://redis:6379
+ exec usr/local/openresty/bin/openresty -g - daemon off
nginx: invalid option: "daemon"
+ '[' == true ']'
/entrypoint.sh: line 5: [: ==: unary operator expected

I believe it is a bash error related to the assignment in entrypoint.sh.

Thanks for your help

**Comment by parisk** [comment]
The reason you are running into the above issue is that `CERYX_DEBUG` is not set, as configuration is not built into images.

This is an intentional decision, as we believe that configuration should not be part of the build artifact (the Docker image in this case). In addition to this, since Ceryx is comprised of 2 components (Proxy + API). That's why you either need Docker Compose or Docker Swarm mode to run it., this would require us to manage duplicate defaults in each image, which we intentionally avoid.

🙌 **Heads up though!** Following the instructions in the [docs](https://github.com/sourcelair/ceryx#running-ceryx) should do the work for you without needing any configuration to get started 😄.
