### ISSUE TITLE
Some robustness questions

### ISSUE THREAD

**Issue by fpemud** [sourcelair/ceryx#80]
1. Can ceryx auto delete route after the client who adds it terminates?
2. Does the client need to re-add the route when ceryx restarts?
3. Does ceryx relies on that redis is always available and data in redis will never be lost?
4. Can I run multipe ceryx instance for load balancing? Then what "ceryx-api-host" should be when calling its API? I think the IP of any instance is OK since each instance will save to the same Redis, right?

Thanks.

**Comment by parisk** [comment]
> Can ceryx auto delete route after the client who adds it terminates?

The Open Source version of Ceryx does not do so. It just handles proxying, redirecting and certificates and also provides you with an API to do so. We are building such features in a commercial version of Ceryx targeted to Kubernetes and Docker Swarm users. We can set up for a free private beta for you, if you are interested.

> Does the client need to re-add the route when ceryx restarts?

If the data is available in Redis, then no. The default setup of Ceryx is for Redis to store data permanently also, so no 😄:

https://github.com/sourcelair/ceryx/blob/d4da17e44b92e2a66b4917bf666b3d4e293726d0/docker-compose.yml#L41-L44

> Does ceryx relies on that redis is always available and data in redis will never be lost?

Yes. Is that an issue with your setup?

> Can I run multipe ceryx instance for load balancing? Then what "ceryx-api-host" should be when calling its API? I think the IP of any instance is OK since each instance will save to the same Redis, right?

Yes you can, although we recommend offloading load balancing duties to Docker Swarm or Kubernetes networking, unless your setup does allow to do so. Can you let us know what is your setup, if it's not Docker Swarm or Kubernetes?

---

I am closing this issue, since all questions have been answered now. Feel free to follow up to my replies above though. We would love to continue the conversation.
